### ISSUE TITLE
User-built waithax 3dsx skips over overflow process for no reason

### ISSUE THREAD

**Issue by codeHusky** [Mrrraou/waithax#7]
If I download a copy of this repo and build it, then deploy it to my 3DS, it just skips over the overflow process. It doesn't bother to try to do anything. It works in Citra for some reason, though.

**Comment by Mrrraou** [comment]
1. you butchered it
2. testing kernel exploits in citra definitely is stupid

here's your issue anyway: https://github.com/MikaalSky/waithax/blob/master/source/waithax.c#L160

if you don't know what you're doing, you shouldn't be doing this.

this isn't an issue with my repo. closed, and please stop making stupid/useless/nonsense issues.

**Comment by codeHusky** [comment]
Shame on me for being curious.

**Comment by codeHusky** [comment]
Plus, your legitimate version of the code untouched does NOT run when I compile it.

**Comment by SonyUSA** [comment]
Works fine for me and literally everyone else, check your build tools

**Comment by codeHusky** [comment]
Will do that tonight.

**Comment by Mrrraou** [comment]
> Plus, your legitimate version of the code untouched does NOT run when I compile it.

i'm sorry, but you fucked something up. plus being curious does not mean butchering up stuff. only edit the code if you totally understand what it does. everyone can build it fine, you're the only one with that pseudo-issue.

**Comment by codeHusky** [comment]
Yeah, it's perfectly possible to not consider every bit of the code when you make an edit to someone else's code. That just happens. If you didn't want dumb questions like this, you shouldn't have issues open on your repo.

**Comment by Mrrraou** [comment]
i'm sorry but at least i know what i'm doing. i'm not responsible for your modifications not working. if you want to edit it, you're on your own with that. i built my code from scratch, and i have tested it multiple times, and a lot of people have been using it. the github issues here are not for techsupport or development support for what you butchered on your own fork. i know what you broke just by reading your fork. you don't even know how to use Git.

i will now be locking this issue, you're getting pretty annoying.

**Comment by kitlith** [comment]
@MikaalSky That's not... *siiiiigh*

Issues are open if/when some legimitate issues come about. In fact, there are two open right now that are being worked on, though, iirc, the guess is that they're related. You don't close issues off on the entire repo to prevent 'dumb questions', you just mark them as invalid and close them. Which is what Mrrraou did.

As for possible environment issues, I'd reccomend grabbing ctrulib from latest git master if you haven't already, and if you want someone to be able to actually be able to troubleshoot something they can't reproduce, or something that might have something to do with the environment, sending a buildlog in the future using something like [hastebin](http://hastebin.com/) so that they can take a look and see what might be wrong.

The other thing I'd reccomend is making sure that waithax_debug(true) is *not* called, as that'll attempt to skip the refcount on pre-hacked systems for debugging and for developers.

**Comment by Mrrraou** [comment]
also, do a clean git clone and try compiling again, lol.

the debug mode patches the refcount with svcbackdoor instead of overflowing it which makes everything faster, so it skips the waitsyncn refcount overflow. intended for development and debugging, yeah.

now locking again.
